#pragma once
#include "common.hpp"
#include "grid.hpp"
#include "localizer.hpp"
#include "tof.hpp"

namespace robot_slamd {

void write_run_metrics(const std::string &path, const RunMetrics &m, const Localizer &loc, const ChunkedGrid &grid, const TofHealth &health, const Config &cfg, const EncoderStats &encoder_stats) {
    auto gs = grid.stats(cfg);
    std::ofstream o(path);
    o << "key,value\n";
    o << "localization_updates," << m.localization_updates << "\n";
    o << "tof_samples," << m.tof_samples << "\n";
    o << "tof_hit_updates," << m.tof_hit_updates << "\n";
    o << "tof_free_only," << m.tof_free_only << "\n";
    o << "tof_rejected," << m.tof_rejected << "\n";
    o << "map_updates," << m.map_updates << "\n";
    o << "map_alloc_failures," << m.map_alloc_failures << "\n";
    o << "map_quality_score_last," << m.map_quality.score_last << "\n";
    o << "map_quality_score_min," << (m.map_quality.score_count ? m.map_quality.score_min : 0.0) << "\n";
    o << "map_quality_score_mean," << (m.map_quality.score_count ? m.map_quality.score_sum / m.map_quality.score_count : 0.0) << "\n";
    o << "map_quality_low_count," << m.map_quality.low_count << "\n";
    o << "map_quality_degraded_count," << m.map_quality.degraded_count << "\n";
    o << "active_scan_recommended_count," << m.map_quality.active_scan_recommended_count << "\n";
    o << "tof_valid_ratio_last," << m.map_quality.tof_valid_ratio_last << "\n";
    o << "tof_reject_ratio_last," << m.map_quality.tof_reject_ratio_last << "\n";
    o << "map_update_rate_hz_last," << m.map_quality.map_update_rate_hz_last << "\n";
    o << "map_known_cells_last," << m.map_quality.map_known_cells_last << "\n";
    o << "map_occupied_cells_last," << m.map_quality.map_occupied_cells_last << "\n";
    o << "supervisor_state_last," << m.mapping_supervisor.state_last << "\n";
    o << "supervisor_state_changes," << m.mapping_supervisor.state_changes << "\n";
    o << "supervisor_mapping_seconds," << m.mapping_supervisor.mapping_seconds << "\n";
    o << "supervisor_active_scan_recommended_count," << m.mapping_supervisor.active_scan_recommended_count << "\n";
    o << "supervisor_degraded_count," << m.mapping_supervisor.degraded_count << "\n";
    o << "supervisor_lost_count," << m.mapping_supervisor.lost_count << "\n";
    o << "supervisor_active_scan_recommended_seconds," << m.mapping_supervisor.active_scan_recommended_seconds << "\n";
    o << "supervisor_degraded_seconds," << m.mapping_supervisor.degraded_seconds << "\n";
    o << "supervisor_lost_seconds," << m.mapping_supervisor.lost_seconds << "\n";
    o << "supervisor_last_reason," << m.mapping_supervisor.last_reason << "\n";
    o << "active_scan_state_last," << m.active_scan.state_last << "\n";
    o << "active_scan_state_changes," << m.active_scan.state_changes << "\n";
    o << "active_scan_request_count," << m.active_scan.request_count << "\n";
    o << "active_scan_would_start_count," << m.active_scan.would_start_count << "\n";
    o << "active_scan_blocked_count," << m.active_scan.blocked_count << "\n";
    o << "active_scan_completed_count," << m.active_scan.completed_count << "\n";
    o << "active_scan_useful_observed_count," << m.active_scan.useful_observed_count << "\n";
    o << "active_scan_recommended_seconds," << m.active_scan.recommended_seconds << "\n";
    o << "active_scan_observing_seconds," << m.active_scan.observing_seconds << "\n";
    o << "active_scan_cooldown_seconds," << m.active_scan.cooldown_seconds << "\n";
    o << "active_scan_blocked_seconds," << m.active_scan.blocked_seconds << "\n";
    o << "active_scan_last_request_type," << m.active_scan.last_request_type << "\n";
    o << "active_scan_last_reason," << m.active_scan.last_reason << "\n";
    o << "active_scan_last_observed_yaw_delta_deg," << m.active_scan.last_observed_yaw_delta_deg << "\n";
    o << "active_scan_max_observed_yaw_delta_deg," << m.active_scan.max_observed_yaw_delta_deg << "\n";
    o << "active_scan_execution_state_last," << m.active_scan_command.state_last << "\n";
    o << "active_scan_execution_state_changes," << m.active_scan_command.state_changes << "\n";
    o << "active_scan_execution_precheck_count," << m.active_scan_command.precheck_count << "\n";
    o << "active_scan_execution_command_start_count," << m.active_scan_command.command_start_count << "\n";
    o << "active_scan_execution_zero_command_count," << m.active_scan_command.zero_command_count << "\n";
    o << "active_scan_execution_completed_count," << m.active_scan_command.completed_count << "\n";
    o << "active_scan_execution_aborted_count," << m.active_scan_command.aborted_count << "\n";
    o << "active_scan_execution_blocked_count," << m.active_scan_command.blocked_count << "\n";
    o << "active_scan_execution_command_active_seconds," << m.active_scan_command.command_active_seconds << "\n";
    o << "active_scan_execution_verifying_seconds," << m.active_scan_command.verifying_seconds << "\n";
    o << "active_scan_execution_cooldown_seconds," << m.active_scan_command.cooldown_seconds << "\n";
    o << "active_scan_execution_blocked_seconds," << m.active_scan_command.blocked_seconds << "\n";
    o << "active_scan_execution_last_reason," << m.active_scan_command.last_reason << "\n";
    o << "active_scan_execution_last_request_type," << m.active_scan_command.last_request_type << "\n";
    o << "active_scan_execution_last_observed_yaw_delta_deg," << m.active_scan_command.last_observed_yaw_delta_deg << "\n";
    o << "active_scan_execution_max_observed_yaw_delta_deg," << m.active_scan_command.max_observed_yaw_delta_deg << "\n";
    o << "sparse_scan_state_last," << m.sparse_scan.state_last << "\n";
    o << "sparse_scan_sessions_started," << m.sparse_scan.sessions_started << "\n";
    o << "sparse_scan_sessions_completed," << m.sparse_scan.sessions_completed << "\n";
    o << "sparse_scan_sessions_aborted," << m.sparse_scan.sessions_aborted << "\n";
    o << "sparse_scan_useful_sessions," << m.sparse_scan.useful_sessions << "\n";
    o << "sparse_scan_complete_sessions," << m.sparse_scan.complete_sessions << "\n";
    o << "sparse_scan_total_samples," << m.sparse_scan.total_samples << "\n";
    o << "sparse_scan_valid_samples," << m.sparse_scan.valid_samples << "\n";
    o << "sparse_scan_invalid_samples," << m.sparse_scan.invalid_samples << "\n";
    o << "sparse_scan_front_valid," << m.sparse_scan.front_valid << "\n";
    o << "sparse_scan_left_valid," << m.sparse_scan.left_valid << "\n";
    o << "sparse_scan_right_valid," << m.sparse_scan.right_valid << "\n";
    o << "sparse_scan_last_observed_yaw_delta_deg," << m.sparse_scan.last_observed_yaw_delta_deg << "\n";
    o << "sparse_scan_max_observed_yaw_delta_deg," << m.sparse_scan.max_observed_yaw_delta_deg << "\n";
    o << "sparse_scan_last_valid_bin_ratio," << m.sparse_scan.last_valid_bin_ratio << "\n";
    o << "sparse_scan_mean_valid_bin_ratio," << (m.sparse_scan.valid_bin_ratio_count ? m.sparse_scan.valid_bin_ratio_sum / m.sparse_scan.valid_bin_ratio_count : 0.0) << "\n";
    o << "yaw_match_attempts," << m.sparse_scan_yaw_match.attempts << "\n";
    o << "yaw_match_usable_count," << m.sparse_scan_yaw_match.usable_count << "\n";
    o << "yaw_match_rejected_count," << m.sparse_scan_yaw_match.rejected_count << "\n";
    o << "yaw_match_last_best_yaw_delta_deg," << m.sparse_scan_yaw_match.last_best_yaw_delta_deg << "\n";
    o << "yaw_match_last_best_score," << m.sparse_scan_yaw_match.last_best_score << "\n";
    o << "yaw_match_last_score_margin," << m.sparse_scan_yaw_match.last_score_margin << "\n";
    o << "yaw_match_last_inlier_ratio," << m.sparse_scan_yaw_match.last_inlier_ratio << "\n";
    o << "yaw_match_last_usable," << (m.sparse_scan_yaw_match.last_usable ? 1 : 0) << "\n";
    o << "yaw_match_last_reason," << m.sparse_scan_yaw_match.last_reason << "\n";
    o << "yaw_match_curve_flat_count," << m.sparse_scan_yaw_match.curve_flat_count << "\n";
    o << "yaw_match_multimodal_count," << m.sparse_scan_yaw_match.multimodal_count << "\n";
    o << "yaw_match_insufficient_data_count," << m.sparse_scan_yaw_match.insufficient_data_count << "\n";
    o << "yaw_correction_state_last," << m.yaw_correction.state_last << "\n";
    o << "yaw_correction_candidates_seen," << m.yaw_correction.candidates_seen << "\n";
    o << "yaw_correction_would_apply_count," << m.yaw_correction.would_apply_count << "\n";
    o << "yaw_correction_rejected_count," << m.yaw_correction.rejected_count << "\n";
    o << "yaw_correction_last_candidate_deg," << m.yaw_correction.last_candidate_deg << "\n";
    o << "yaw_correction_last_suggested_correction_deg," << m.yaw_correction.last_suggested_correction_deg << "\n";
    o << "yaw_correction_last_reason," << m.yaw_correction.last_reason << "\n";
    o << "yaw_correction_consistency_count_last," << m.yaw_correction.consistency_count_last << "\n";
    o << "yaw_correction_consistency_spread_deg_last," << m.yaw_correction.consistency_spread_deg_last << "\n";
    o << "yaw_correction_robot_moving_reject_count," << m.yaw_correction.robot_moving_reject_count << "\n";
    o << "yaw_correction_low_quality_reject_count," << m.yaw_correction.low_quality_reject_count << "\n";
    o << "yaw_correction_consistency_reject_count," << m.yaw_correction.consistency_reject_count << "\n";
    o << "yaw_correction_scan_evidence_reject_count," << m.yaw_correction.scan_evidence_reject_count << "\n";
    o << "yaw_correction_active_scan_evidence_reject_count," << m.yaw_correction.active_scan_evidence_reject_count << "\n";
    o << "yaw_correction_yaw_match_evidence_reject_count," << m.yaw_correction.yaw_match_evidence_reject_count << "\n";
    o << "yaw_correction_last_scan_evidence_ok," << (m.yaw_correction.last_scan_evidence_ok ? 1 : 0) << "\n";
    o << "yaw_correction_last_active_scan_evidence_ok," << (m.yaw_correction.last_active_scan_evidence_ok ? 1 : 0) << "\n";
    o << "yaw_correction_last_yaw_match_evidence_ok," << (m.yaw_correction.last_yaw_match_evidence_ok ? 1 : 0) << "\n";
    o << "yaw_correction_last_match_observed_yaw_delta_deg," << m.yaw_correction.last_match_observed_yaw_delta_deg << "\n";
    o << "yaw_correction_last_match_valid_samples," << m.yaw_correction.last_match_valid_samples << "\n";
    o << "yaw_correction_last_match_valid_bins," << m.yaw_correction.last_match_valid_bins << "\n";
    o << "yaw_correction_last_match_valid_bin_ratio," << m.yaw_correction.last_match_valid_bin_ratio << "\n";
    o << "yaw_correction_apply_attempts," << m.yaw_correction_apply.attempts << "\n";
    o << "yaw_correction_apply_success_count," << m.yaw_correction_apply.success_count << "\n";
    o << "yaw_correction_apply_rejected_count," << m.yaw_correction_apply.rejected_count << "\n";
    o << "yaw_correction_apply_last_applied," << (m.yaw_correction_apply.last_applied ? 1 : 0) << "\n";
    o << "yaw_correction_apply_last_reason," << m.yaw_correction_apply.last_reason << "\n";
    o << "yaw_correction_apply_last_delta_deg," << m.yaw_correction_apply.last_delta_deg << "\n";
    o << "yaw_correction_apply_last_old_yaw_rad," << m.yaw_correction_apply.last_old_yaw_rad << "\n";
    o << "yaw_correction_apply_last_new_yaw_rad," << m.yaw_correction_apply.last_new_yaw_rad << "\n";
    o << "yaw_correction_apply_session_count," << m.yaw_correction_apply.session_count << "\n";
    o << "yaw_correction_apply_session_total_abs_deg," << m.yaw_correction_apply.session_total_abs_deg << "\n";
    o << "yaw_correction_apply_cooldown_reject_count," << m.yaw_correction_apply.cooldown_reject_count << "\n";
    o << "yaw_correction_apply_gate_reject_count," << m.yaw_correction_apply.gate_reject_count << "\n";
    o << "yaw_correction_apply_safety_reject_count," << m.yaw_correction_apply.safety_reject_count << "\n";
    o << "static_scan_boost_updates," << m.static_scan_boost_updates << "\n";
    o << "low_odom_quality_pauses," << m.low_odom_quality_pauses << "\n";
    o << "tof_unhealthy_pauses," << m.tof_unhealthy_pauses << "\n";
    o << "tof_correction_attempts," << m.tof_correction_attempts << "\n";
    o << "tof_correction_accepts," << m.tof_correction_accepts << "\n";
    o << "tof_correction_rejects," << m.tof_correction_rejects << "\n";
    o << "tof_correction_mean_residual," << (m.tof_correction_attempts ? m.tof_correction_residual_sum / m.tof_correction_attempts : 0.0) << "\n";
    o << "tof_correction_odom_residual_mean," << (m.tof_correction_attempts ? m.tof_correction_odom_residual_sum / m.tof_correction_attempts : 0.0) << "\n";
    o << "tof_correction_best_residual_mean," << (m.tof_correction_attempts ? m.tof_correction_residual_sum / m.tof_correction_attempts : 0.0) << "\n";
    o << "tof_correction_improvement_mean," << (m.tof_correction_attempts ? m.tof_correction_improvement_sum / m.tof_correction_attempts : 0.0) << "\n";
    o << "tof_correction_best_shift_mean," << (m.tof_correction_attempts ? m.tof_correction_best_shift_sum / m.tof_correction_attempts : 0.0) << "\n";
    o << "tof_correction_max_dx," << m.tof_correction_max_dx << "\n";
    o << "tof_correction_max_dyaw," << m.tof_correction_max_dyaw << "\n";
    o << "pose_quality_mean," << (m.localization_updates ? m.pose_quality_sum / m.localization_updates : 0.0) << "\n";
    o << "pose_quality_min," << (m.localization_updates ? m.pose_quality_min : 0.0) << "\n";
    o << "localization_confidence_mean," << (m.localization_updates ? m.localization_confidence_sum / m.localization_updates : 0.0) << "\n";
    o << "localization_confidence_min," << (m.localization_updates ? m.localization_confidence_min : 0.0) << "\n";
    o << "spin_scan_attempts," << m.spin_scan_attempts << "\n";
    o << "spin_scan_completed," << m.spin_scan_completed << "\n";
    o << "spin_scan_failed," << m.spin_scan_failed << "\n";
    o << "spin_scan_matched," << m.spin_scan_matched << "\n";
    o << "spin_scan_usable," << m.spin_scan_usable << "\n";
    o << "spin_scan_valid_bins_mean," << (m.spin_scan_attempts ? m.spin_scan_valid_bins_sum / m.spin_scan_attempts : 0.0) << "\n";
    o << "spin_scan_valid_bin_ratio_mean," << (m.spin_scan_attempts ? m.spin_scan_valid_bin_ratio_sum / m.spin_scan_attempts : 0.0) << "\n";
    o << "spin_scan_reliability_mean," << (m.spin_scan_attempts ? m.spin_scan_reliability_sum / m.spin_scan_attempts : 0.0) << "\n";
    o << "spin_scan_reliability_min," << (m.spin_scan_attempts ? m.spin_scan_reliability_min : 0.0) << "\n";
    o << "spin_scan_multimodal_count," << m.spin_scan_multimodal_count << "\n";
    o << "spin_scan_flat_curve_count," << m.spin_scan_flat_curve_count << "\n";
    o << "spin_scan_edge_best_count," << m.spin_scan_edge_best_count << "\n";
    o << "encoder_rejected_updates," << loc.rejected_encoder_updates() << "\n";
    o << "encoder_left_reads," << encoder_stats.left_reads << "\n";
    o << "encoder_right_reads," << encoder_stats.right_reads << "\n";
    o << "encoder_left_errors," << encoder_stats.left_errors << "\n";
    o << "encoder_right_errors," << encoder_stats.right_errors << "\n";
    o << "encoder_left_total_ticks," << encoder_stats.left_total_ticks << "\n";
    o << "encoder_right_total_ticks," << encoder_stats.right_total_ticks << "\n";
    o << "encoder_left_rpm," << encoder_stats.left_rpm << "\n";
    o << "encoder_right_rpm," << encoder_stats.right_rpm << "\n";
    o << "encoder_uart_checksum_errors," << encoder_stats.uart_checksum_errors << "\n";
    o << "encoder_uart_timeout_errors," << encoder_stats.uart_timeout_errors << "\n";
    o << "encoder_uart_status_errors," << encoder_stats.uart_status_errors << "\n";
    o << "encoder_uart_frame_errors," << encoder_stats.uart_frame_errors << "\n";
    o << "encoder_jump_rejects," << encoder_stats.jump_rejects << "\n";
    o << "encoder_left_unhealthy," << (encoder_stats.left_unhealthy ? 1 : 0) << "\n";
    o << "encoder_right_unhealthy," << (encoder_stats.right_unhealthy ? 1 : 0) << "\n";
    o << "gyro_spikes," << loc.gyro_spikes() << "\n";
    o << "gyro_bias_adapt_updates," << loc.bias_adapt_updates() << "\n";
    o << "final_gyro_bias_rad_s," << loc.gyro_bias() << "\n";
    for (const auto &id : {"front", "left", "right"}) {
        const auto &st = health.by_id.at(id);
        o << id << "_hit_rate," << st.hit_rate() << "\n";
        o << id << "_reject_rate," << st.reject_rate() << "\n";
        o << id << "_gap_count," << st.gaps << "\n";
        o << id << "_confidence_mean," << st.confidence_mean() << "\n";
        o << id << "_unhealthy," << (st.unhealthy(cfg) ? 1 : 0) << "\n";
    }
    o << "map_chunks," << gs.chunks << "\n";
    o << "map_touched_cells," << gs.touched_cells << "\n";
    o << "map_width_cells," << gs.width_cells << "\n";
    o << "map_height_cells," << gs.height_cells << "\n";
    o << "map_occupied_cells," << gs.occupied_cells << "\n";
    o << "map_free_cells," << gs.free_cells << "\n";
    o << "map_unknown_cells," << gs.unknown_cells << "\n";
}

} // namespace robot_slamd
