#pragma once
#include "robot_slamd/core/common.hpp"
#include "robot_slamd/core/grid.hpp"
#include "robot_slamd/mapping/localizer.hpp"
#include "robot_slamd/sensors/tof.hpp"
#include "robot_slamd/core/software_motion_metrics_writer.hpp"

namespace robot_slamd {

void write_run_metrics(const std::string &path, const RunMetrics &m, const Localizer &loc, const ChunkedGrid &grid, const TofHealth &health, const Config &cfg, const EncoderStats &encoder_stats) {
    auto gs = grid.stats(cfg);
    std::ofstream o(path);
    o << "key,value\n";
    o << "localization_updates," << m.localization_updates << "\n";
    o << "tof_samples," << m.tof_samples << "\n";
    o << "tof_hit_updates," << m.tof_hit_updates << "\n";
    o << "tof_free_only," << m.tof_free_only << "\n";
    o << "tof_rejected," << m.tof_rejected << "\n";
    o << "map_updates," << m.map_updates << "\n";
    o << "map_alloc_failures," << m.map_alloc_failures << "\n";
    o << "map_quality_score_last," << m.map_quality.score_last << "\n";
    o << "map_quality_score_min," << (m.map_quality.score_count ? m.map_quality.score_min : 0.0) << "\n";
    o << "map_quality_score_mean," << (m.map_quality.score_count ? m.map_quality.score_sum / m.map_quality.score_count : 0.0) << "\n";
    o << "map_quality_low_count," << m.map_quality.low_count << "\n";
    o << "map_quality_degraded_count," << m.map_quality.degraded_count << "\n";
    o << "active_scan_recommended_count," << m.map_quality.active_scan_recommended_count << "\n";
    o << "tof_valid_ratio_last," << m.map_quality.tof_valid_ratio_last << "\n";
    o << "tof_reject_ratio_last," << m.map_quality.tof_reject_ratio_last << "\n";
    o << "map_update_rate_hz_last," << m.map_quality.map_update_rate_hz_last << "\n";
    o << "map_known_cells_last," << m.map_quality.map_known_cells_last << "\n";
    o << "map_occupied_cells_last," << m.map_quality.map_occupied_cells_last << "\n";
    o << "supervisor_state_last," << m.mapping_supervisor.state_last << "\n";
    o << "supervisor_state_changes," << m.mapping_supervisor.state_changes << "\n";
    o << "supervisor_mapping_seconds," << m.mapping_supervisor.mapping_seconds << "\n";
    o << "supervisor_active_scan_recommended_count," << m.mapping_supervisor.active_scan_recommended_count << "\n";
    o << "supervisor_degraded_count," << m.mapping_supervisor.degraded_count << "\n";
    o << "supervisor_lost_count," << m.mapping_supervisor.lost_count << "\n";
    o << "supervisor_active_scan_recommended_seconds," << m.mapping_supervisor.active_scan_recommended_seconds << "\n";
    o << "supervisor_degraded_seconds," << m.mapping_supervisor.degraded_seconds << "\n";
    o << "supervisor_lost_seconds," << m.mapping_supervisor.lost_seconds << "\n";
    o << "supervisor_last_reason," << m.mapping_supervisor.last_reason << "\n";
    o << "active_scan_state_last," << m.active_scan.state_last << "\n";
    o << "active_scan_state_changes," << m.active_scan.state_changes << "\n";
    o << "active_scan_request_count," << m.active_scan.request_count << "\n";
    o << "active_scan_would_start_count," << m.active_scan.would_start_count << "\n";
    o << "active_scan_blocked_count," << m.active_scan.blocked_count << "\n";
    o << "active_scan_completed_count," << m.active_scan.completed_count << "\n";
    o << "active_scan_useful_observed_count," << m.active_scan.useful_observed_count << "\n";
    o << "active_scan_recommended_seconds," << m.active_scan.recommended_seconds << "\n";
    o << "active_scan_observing_seconds," << m.active_scan.observing_seconds << "\n";
    o << "active_scan_cooldown_seconds," << m.active_scan.cooldown_seconds << "\n";
    o << "active_scan_blocked_seconds," << m.active_scan.blocked_seconds << "\n";
    o << "active_scan_last_request_type," << m.active_scan.last_request_type << "\n";
    o << "active_scan_last_reason," << m.active_scan.last_reason << "\n";
    o << "active_scan_last_observed_yaw_delta_deg," << m.active_scan.last_observed_yaw_delta_deg << "\n";
    o << "active_scan_max_observed_yaw_delta_deg," << m.active_scan.max_observed_yaw_delta_deg << "\n";
    o << "active_scan_execution_state_last," << m.active_scan_command.state_last << "\n";
    o << "active_scan_execution_state_changes," << m.active_scan_command.state_changes << "\n";
    o << "active_scan_execution_precheck_count," << m.active_scan_command.precheck_count << "\n";
    o << "active_scan_execution_command_start_count," << m.active_scan_command.command_start_count << "\n";
    o << "active_scan_execution_zero_command_count," << m.active_scan_command.zero_command_count << "\n";
    o << "active_scan_execution_completed_count," << m.active_scan_command.completed_count << "\n";
    o << "active_scan_execution_aborted_count," << m.active_scan_command.aborted_count << "\n";
    o << "active_scan_execution_blocked_count," << m.active_scan_command.blocked_count << "\n";
    o << "active_scan_execution_command_active_seconds," << m.active_scan_command.command_active_seconds << "\n";
    o << "active_scan_execution_verifying_seconds," << m.active_scan_command.verifying_seconds << "\n";
    o << "active_scan_execution_cooldown_seconds," << m.active_scan_command.cooldown_seconds << "\n";
    o << "active_scan_execution_blocked_seconds," << m.active_scan_command.blocked_seconds << "\n";
    o << "active_scan_execution_last_reason," << m.active_scan_command.last_reason << "\n";
    o << "active_scan_execution_last_request_type," << m.active_scan_command.last_request_type << "\n";
    o << "active_scan_execution_last_observed_yaw_delta_deg," << m.active_scan_command.last_observed_yaw_delta_deg << "\n";
    o << "active_scan_execution_max_observed_yaw_delta_deg," << m.active_scan_command.max_observed_yaw_delta_deg << "\n";
    o << "sparse_scan_state_last," << m.sparse_scan.state_last << "\n";
    o << "sparse_scan_sessions_started," << m.sparse_scan.sessions_started << "\n";
    o << "sparse_scan_sessions_completed," << m.sparse_scan.sessions_completed << "\n";
    o << "sparse_scan_sessions_aborted," << m.sparse_scan.sessions_aborted << "\n";
    o << "sparse_scan_useful_sessions," << m.sparse_scan.useful_sessions << "\n";
    o << "sparse_scan_complete_sessions," << m.sparse_scan.complete_sessions << "\n";
    o << "sparse_scan_total_samples," << m.sparse_scan.total_samples << "\n";
    o << "sparse_scan_valid_samples," << m.sparse_scan.valid_samples << "\n";
    o << "sparse_scan_invalid_samples," << m.sparse_scan.invalid_samples << "\n";
    o << "sparse_scan_front_valid," << m.sparse_scan.front_valid << "\n";
    o << "sparse_scan_left_valid," << m.sparse_scan.left_valid << "\n";
    o << "sparse_scan_right_valid," << m.sparse_scan.right_valid << "\n";
    o << "sparse_scan_last_observed_yaw_delta_deg," << m.sparse_scan.last_observed_yaw_delta_deg << "\n";
    o << "sparse_scan_max_observed_yaw_delta_deg," << m.sparse_scan.max_observed_yaw_delta_deg << "\n";
    o << "sparse_scan_last_valid_bin_ratio," << m.sparse_scan.last_valid_bin_ratio << "\n";
    o << "sparse_scan_mean_valid_bin_ratio," << (m.sparse_scan.valid_bin_ratio_count ? m.sparse_scan.valid_bin_ratio_sum / m.sparse_scan.valid_bin_ratio_count : 0.0) << "\n";
    o << "yaw_match_attempts," << m.sparse_scan_yaw_match.attempts << "\n";
    o << "yaw_match_usable_count," << m.sparse_scan_yaw_match.usable_count << "\n";
    o << "yaw_match_rejected_count," << m.sparse_scan_yaw_match.rejected_count << "\n";
    o << "yaw_match_last_best_yaw_delta_deg," << m.sparse_scan_yaw_match.last_best_yaw_delta_deg << "\n";
    o << "yaw_match_last_best_score," << m.sparse_scan_yaw_match.last_best_score << "\n";
    o << "yaw_match_last_score_margin," << m.sparse_scan_yaw_match.last_score_margin << "\n";
    o << "yaw_match_last_inlier_ratio," << m.sparse_scan_yaw_match.last_inlier_ratio << "\n";
    o << "yaw_match_last_usable," << (m.sparse_scan_yaw_match.last_usable ? 1 : 0) << "\n";
    o << "yaw_match_last_reason," << m.sparse_scan_yaw_match.last_reason << "\n";
    o << "yaw_match_curve_flat_count," << m.sparse_scan_yaw_match.curve_flat_count << "\n";
    o << "yaw_match_multimodal_count," << m.sparse_scan_yaw_match.multimodal_count << "\n";
    o << "yaw_match_insufficient_data_count," << m.sparse_scan_yaw_match.insufficient_data_count << "\n";
    o << "yaw_correction_state_last," << m.yaw_correction.state_last << "\n";
    o << "yaw_correction_candidates_seen," << m.yaw_correction.candidates_seen << "\n";
    o << "yaw_correction_would_apply_count," << m.yaw_correction.would_apply_count << "\n";
    o << "yaw_correction_rejected_count," << m.yaw_correction.rejected_count << "\n";
    o << "yaw_correction_last_candidate_deg," << m.yaw_correction.last_candidate_deg << "\n";
    o << "yaw_correction_last_suggested_correction_deg," << m.yaw_correction.last_suggested_correction_deg << "\n";
    o << "yaw_correction_last_reason," << m.yaw_correction.last_reason << "\n";
    o << "yaw_correction_consistency_count_last," << m.yaw_correction.consistency_count_last << "\n";
    o << "yaw_correction_consistency_spread_deg_last," << m.yaw_correction.consistency_spread_deg_last << "\n";
    o << "yaw_correction_robot_moving_reject_count," << m.yaw_correction.robot_moving_reject_count << "\n";
    o << "yaw_correction_low_quality_reject_count," << m.yaw_correction.low_quality_reject_count << "\n";
    o << "yaw_correction_consistency_reject_count," << m.yaw_correction.consistency_reject_count << "\n";
    o << "yaw_correction_scan_evidence_reject_count," << m.yaw_correction.scan_evidence_reject_count << "\n";
    o << "yaw_correction_active_scan_evidence_reject_count," << m.yaw_correction.active_scan_evidence_reject_count << "\n";
    o << "yaw_correction_yaw_match_evidence_reject_count," << m.yaw_correction.yaw_match_evidence_reject_count << "\n";
    o << "yaw_correction_last_scan_evidence_ok," << (m.yaw_correction.last_scan_evidence_ok ? 1 : 0) << "\n";
    o << "yaw_correction_last_active_scan_evidence_ok," << (m.yaw_correction.last_active_scan_evidence_ok ? 1 : 0) << "\n";
    o << "yaw_correction_last_yaw_match_evidence_ok," << (m.yaw_correction.last_yaw_match_evidence_ok ? 1 : 0) << "\n";
    o << "yaw_correction_last_match_observed_yaw_delta_deg," << m.yaw_correction.last_match_observed_yaw_delta_deg << "\n";
    o << "yaw_correction_last_match_valid_samples," << m.yaw_correction.last_match_valid_samples << "\n";
    o << "yaw_correction_last_match_valid_bins," << m.yaw_correction.last_match_valid_bins << "\n";
    o << "yaw_correction_last_match_valid_bin_ratio," << m.yaw_correction.last_match_valid_bin_ratio << "\n";
    o << "yaw_correction_gate_apply_feedback_count," << m.yaw_correction.apply_feedback_count << "\n";
    o << "yaw_correction_gate_window_reset_count," << m.yaw_correction.window_reset_count << "\n";
    o << "yaw_correction_gate_last_applied_scan_id," << m.yaw_correction.last_applied_scan_id << "\n";
    o << "yaw_correction_gate_last_applied_delta_deg," << m.yaw_correction.last_applied_delta_deg << "\n";
    o << "yaw_correction_apply_attempts," << m.yaw_correction_apply.attempts << "\n";
    o << "yaw_correction_apply_success_count," << m.yaw_correction_apply.success_count << "\n";
    o << "yaw_correction_apply_rejected_count," << m.yaw_correction_apply.rejected_count << "\n";
    o << "yaw_correction_apply_last_applied," << (m.yaw_correction_apply.last_applied ? 1 : 0) << "\n";
    o << "yaw_correction_apply_last_reason," << m.yaw_correction_apply.last_reason << "\n";
    o << "yaw_correction_apply_last_delta_deg," << m.yaw_correction_apply.last_delta_deg << "\n";
    o << "yaw_correction_apply_last_old_yaw_rad," << m.yaw_correction_apply.last_old_yaw_rad << "\n";
    o << "yaw_correction_apply_last_new_yaw_rad," << m.yaw_correction_apply.last_new_yaw_rad << "\n";
    o << "yaw_correction_apply_session_count," << m.yaw_correction_apply.session_count << "\n";
    o << "yaw_correction_apply_session_total_abs_deg," << m.yaw_correction_apply.session_total_abs_deg << "\n";
    o << "yaw_correction_apply_cooldown_reject_count," << m.yaw_correction_apply.cooldown_reject_count << "\n";
    o << "yaw_correction_apply_gate_reject_count," << m.yaw_correction_apply.gate_reject_count << "\n";
    o << "yaw_correction_apply_safety_reject_count," << m.yaw_correction_apply.safety_reject_count << "\n";
    o << "yaw_correction_apply_duplicate_candidate_reject_count," << m.yaw_correction_apply.duplicate_candidate_reject_count << "\n";
    o << "yaw_correction_apply_last_match_scan_id," << m.yaw_correction_apply.last_match_scan_id << "\n";
    o << "yaw_correction_apply_last_match_timestamp_s," << m.yaw_correction_apply.last_match_timestamp_s << "\n";
    o << "yaw_writeback_localization_invalid_reason_last," << m.yaw_correction_apply.localization_invalid_reason_last << "\n";
    o << "yaw_correction_post_apply_validated_count," << m.yaw_correction_post_apply.validated_count << "\n";
    o << "yaw_correction_post_apply_suspect_count," << m.yaw_correction_post_apply.suspect_count << "\n";
    o << "yaw_correction_post_apply_failed_count," << m.yaw_correction_post_apply.failed_count << "\n";
    o << "yaw_correction_post_apply_timeout_count," << m.yaw_correction_post_apply.timeout_count << "\n";
    o << "yaw_correction_post_apply_last_state," << m.yaw_correction_post_apply.last_state << "\n";
    o << "yaw_correction_post_apply_last_reason," << m.yaw_correction_post_apply.last_reason << "\n";
    o << "yaw_correction_post_apply_last_improvement_deg," << m.yaw_correction_post_apply.last_improvement_deg << "\n";
    o << "yaw_correction_post_apply_last_expected_min_improvement_deg," << m.yaw_correction_post_apply.last_expected_min_improvement_deg << "\n";
    o << "yaw_correction_post_apply_last_new_match_timestamp_s," << m.yaw_correction_post_apply.last_new_match_timestamp_s << "\n";
    o << "recovery_state_last," << m.recovery.state_last << "\n";
    o << "recovery_state_changes," << m.recovery.state_changes << "\n";
    o << "recovery_startup_observe_count," << m.recovery.startup_observe_count << "\n";
    o << "recovery_degraded_observe_count," << m.recovery.degraded_observe_count << "\n";
    o << "recovery_lost_observe_count," << m.recovery.lost_observe_count << "\n";
    o << "recovery_scan_recommended_count," << m.recovery.scan_recommended_count << "\n";
    o << "recovery_candidate_seen_count," << m.recovery.candidate_seen_count << "\n";
    o << "recovery_candidate_ready_count," << m.recovery.candidate_ready_count << "\n";
    o << "recovery_rejected_count," << m.recovery.rejected_count << "\n";
    o << "recovery_map_evidence_reject_count," << m.recovery.map_evidence_reject_count << "\n";
    o << "recovery_tof_evidence_reject_count," << m.recovery.tof_evidence_reject_count << "\n";
    o << "recovery_localizer_evidence_reject_count," << m.recovery.localizer_evidence_reject_count << "\n";
    o << "recovery_yaw_match_evidence_reject_count," << m.recovery.yaw_match_evidence_reject_count << "\n";
    o << "recovery_yaw_correction_unstable_reject_count," << m.recovery.yaw_correction_unstable_reject_count << "\n";
    o << "recovery_last_reason," << m.recovery.last_reason << "\n";
    o << "recovery_last_type," << m.recovery.last_type << "\n";
    o << "recovery_last_missing_evidence," << m.recovery.last_missing_evidence << "\n";
    o << "recovery_last_match_scan_id," << m.recovery.last_match_scan_id << "\n";
    o << "recovery_last_yaw_candidate_deg," << m.recovery.last_yaw_candidate_deg << "\n";
    o << "motion_state_last," << m.motion.state_last << "\n";
    o << "motion_state_changes," << m.motion.state_changes << "\n";
    o << "motion_command_seen_count," << m.motion.command_seen_count << "\n";
    o << "motion_would_command_count," << m.motion.would_command_count << "\n";
    o << "motion_would_zero_count," << m.motion.would_zero_count << "\n";
    o << "motion_blocked_count," << m.motion.blocked_count << "\n";
    o << "motion_fault_count," << m.motion.fault_count << "\n";
    o << "motion_obstacle_stop_count," << m.motion.obstacle_stop_count << "\n";
    o << "motion_tof_stale_block_count," << m.motion.tof_stale_block_count << "\n";
    o << "motion_encoder_stale_block_count," << m.motion.encoder_stale_block_count << "\n";
    o << "motion_encoder_read_failed_block_count," << m.motion.encoder_read_failed_block_count << "\n";
    o << "motion_encoder_latency_high_block_count," << m.motion.encoder_latency_high_block_count << "\n";
    o << "motion_encoder_pair_skew_high_block_count," << m.motion.encoder_pair_skew_high_block_count << "\n";
    o << "motion_current_high_block_count," << m.motion.current_high_block_count << "\n";
    o << "motion_status_error_block_count," << m.motion.status_error_block_count << "\n";
    o << "motion_stall_block_count," << m.motion.stall_block_count << "\n";
    o << "motion_supervisor_lost_block_count," << m.motion.supervisor_lost_block_count << "\n";
    o << "motion_last_reason," << m.motion.last_reason << "\n";
    o << "motion_last_target_left_rpm," << m.motion.last_target_left_rpm << "\n";
    o << "motion_last_target_right_rpm," << m.motion.last_target_right_rpm << "\n";
    o << "motion_last_desired_yaw_rate_dps," << m.motion.last_desired_yaw_rate_dps << "\n";
    o << "motion_last_front_distance_m," << m.motion.last_front_distance_m << "\n";
    o << "motion_last_left_distance_m," << m.motion.last_left_distance_m << "\n";
    o << "motion_last_right_distance_m," << m.motion.last_right_distance_m << "\n";
    o << "motion_command_duration_exceeded_count," << m.motion.command_duration_exceeded_count << "\n";
    o << "motion_last_command_session_id," << m.motion.last_command_session_id << "\n";
    o << "motion_last_command_session_duration_s," << m.motion.last_command_session_duration_s << "\n";
    o << "motion_command_stale_count," << m.motion.command_stale_count << "\n";
    o << "motion_deadman_timeout_count," << m.motion.deadman_timeout_count << "\n";
    o << "motion_last_command_age_s," << m.motion.last_command_age_s << "\n";
    o << "motion_last_deadman_age_s," << m.motion.last_deadman_age_s << "\n";
    o << "motion_write_authorization_valid_last," << (m.motion.write_authorization_valid_last ? 1 : 0) << "\n";
    o << "motion_feedback_not_finite_block_count," << m.motion.feedback_not_finite_block_count << "\n";
    o << "motion_wheel_direction_invalid_count," << m.motion.wheel_direction_invalid_count << "\n";
    o << "motion_command_duration_latched_count," << m.motion.command_duration_latched_count << "\n";
    o << "motion_command_duration_latch_active_last," << (m.motion.command_duration_latch_active_last ? 1 : 0) << "\n";
    o << "motion_writer_dispatch_enabled_last," << (m.motion_writer.dispatch_enabled_last ? 1 : 0) << "\n";
    o << "motion_writer_zero_write_count," << m.motion_writer.zero_write_count << "\n";
    o << "motion_writer_rpm_write_count," << m.motion_writer.rpm_write_count << "\n";
    o << "motion_writer_error_count," << m.motion_writer.error_count << "\n";
    o << "motion_writer_last_left_rpm," << m.motion_writer.last_left_rpm << "\n";
    o << "motion_writer_last_right_rpm," << m.motion_writer.last_right_rpm << "\n";
    o << "motion_writer_last_error," << m.motion_writer.last_error << "\n";
    write_software_motion_metrics(o, m, cfg);
    o << "autonomous_slam_enabled_last," << (cfg.autonomous_slam_enabled ? 1 : 0) << "\n";
    o << "autonomous_slam_state_last," << m.autonomous_slam.state_last << "\n";
    o << "autonomous_slam_fault_last," << m.autonomous_slam.fault_last << "\n";
    o << "autonomous_slam_iteration_count_last," << m.autonomous_slam.iteration_count_last << "\n";
    o << "autonomous_slam_command_sent_count," << m.autonomous_slam.command_sent_count << "\n";
    o << "autonomous_slam_stop_sent_count," << m.autonomous_slam.stop_sent_count << "\n";
    o << "autonomous_slam_active_scan_command_count," << m.autonomous_slam.active_scan_command_count << "\n";
    o << "autonomous_slam_sensor_not_ready_count," << m.autonomous_slam.sensor_not_ready_count << "\n";
    o << "autonomous_slam_map_quality_good_count," << m.autonomous_slam.map_quality_good_count << "\n";
    o << "autonomous_slam_map_quality_poor_count," << m.autonomous_slam.map_quality_poor_count << "\n";
    o << "autonomous_slam_motion_reject_count," << m.autonomous_slam.motion_reject_count << "\n";
    o << "autonomous_slam_fault_count," << m.autonomous_slam.fault_count << "\n";
    o << "real_adapter_contract_enabled_last," << (cfg.real_adapter_contract_enabled ? 1 : 0) << "\n";
    o << "real_adapter_contract_check_ok_last," << (m.autonomous_slam.real_adapter_contract_check_ok_last ? 1 : 0) << "\n";
    o << "real_adapter_contract_error_count," << m.autonomous_slam.real_adapter_contract_error_count << "\n";
    o << "real_adapter_contract_warning_count," << m.autonomous_slam.real_adapter_contract_warning_count << "\n";
    o << "real_adapter_readiness_last," << m.autonomous_slam.real_adapter_readiness_last << "\n";
    o << "real_adapter_readiness_error_count," << m.autonomous_slam.real_adapter_readiness_error_count << "\n";
    o << "real_adapter_acceptance_run_count," << m.autonomous_slam.real_adapter_acceptance_run_count << "\n";
    o << "real_adapter_acceptance_pass_count," << m.autonomous_slam.real_adapter_acceptance_pass_count << "\n";
    o << "real_adapter_acceptance_fail_count," << m.autonomous_slam.real_adapter_acceptance_fail_count << "\n";
    o << "real_adapter_tof_frame_ok_last," << (m.autonomous_slam.real_adapter_tof_frame_ok_last ? 1 : 0) << "\n";
    o << "real_adapter_imu_frame_ok_last," << (m.autonomous_slam.real_adapter_imu_frame_ok_last ? 1 : 0) << "\n";
    o << "real_adapter_wheel_frame_ok_last," << (m.autonomous_slam.real_adapter_wheel_frame_ok_last ? 1 : 0) << "\n";
    o << "real_adapter_map_quality_ok_last," << (m.autonomous_slam.real_adapter_map_quality_ok_last ? 1 : 0) << "\n";
    o << "prelive_autonomous_slam_enabled_last," << (cfg.prelive_autonomous_slam_enabled ? 1 : 0) << "\n";
    o << "prelive_autonomous_slam_run_count," << m.autonomous_slam.prelive_autonomous_slam_run_count << "\n";
    o << "prelive_autonomous_slam_ok_last," << (m.autonomous_slam.prelive_autonomous_slam_ok_last ? 1 : 0) << "\n";
    o << "prelive_autonomous_slam_stage_last," << m.autonomous_slam.prelive_autonomous_slam_stage_last << "\n";
    o << "prelive_autonomous_slam_block_reason_last," << m.autonomous_slam.prelive_autonomous_slam_block_reason_last << "\n";
    o << "prelive_autonomous_slam_readiness_last," << m.autonomous_slam.prelive_autonomous_slam_readiness_last << "\n";
    o << "prelive_autonomous_slam_final_state_last," << m.autonomous_slam.prelive_autonomous_slam_final_state_last << "\n";
    o << "prelive_autonomous_slam_final_fault_last," << m.autonomous_slam.prelive_autonomous_slam_final_fault_last << "\n";
    o << "prelive_autonomous_slam_readiness_check_count," << m.autonomous_slam.prelive_autonomous_slam_readiness_check_count << "\n";
    o << "prelive_autonomous_slam_contract_check_count," << m.autonomous_slam.prelive_autonomous_slam_contract_check_count << "\n";
    o << "prelive_autonomous_slam_adapter_acceptance_run_count," << m.autonomous_slam.prelive_autonomous_slam_adapter_acceptance_run_count << "\n";
    o << "prelive_autonomous_slam_coordinator_step_count," << m.autonomous_slam.prelive_autonomous_slam_coordinator_step_count << "\n";
    o << "prelive_autonomous_slam_motion_command_count," << m.autonomous_slam.prelive_autonomous_slam_motion_command_count << "\n";
    o << "prelive_autonomous_slam_stop_command_count," << m.autonomous_slam.prelive_autonomous_slam_stop_command_count << "\n";
    o << "prelive_autonomous_slam_active_scan_command_count," << m.autonomous_slam.prelive_autonomous_slam_active_scan_command_count << "\n";
    o << "prelive_autonomous_slam_motion_reject_count," << m.autonomous_slam.prelive_autonomous_slam_motion_reject_count << "\n";
    o << "prelive_autonomous_slam_coordinator_fault_count," << m.autonomous_slam.prelive_autonomous_slam_coordinator_fault_count << "\n";
    o << "slam_backend_binding_enabled_last," << (cfg.slam_backend_binding_enabled ? 1 : 0) << "\n";
    o << "slam_backend_stage_last," << m.autonomous_slam.slam_backend_stage_last << "\n";
    o << "slam_backend_fault_last," << m.autonomous_slam.slam_backend_fault_last << "\n";
    o << "slam_backend_update_status_last," << m.autonomous_slam.slam_backend_update_status_last << "\n";
    o << "slam_backend_input_check_ok_last," << (m.autonomous_slam.slam_backend_input_check_ok_last ? 1 : 0) << "\n";
    o << "slam_backend_update_check_ok_last," << (m.autonomous_slam.slam_backend_update_check_ok_last ? 1 : 0) << "\n";
    o << "slam_backend_quality_check_ok_last," << (m.autonomous_slam.slam_backend_quality_check_ok_last ? 1 : 0) << "\n";
    o << "slam_backend_acceptance_run_count," << m.autonomous_slam.slam_backend_acceptance_run_count << "\n";
    o << "slam_backend_acceptance_pass_count," << m.autonomous_slam.slam_backend_acceptance_pass_count << "\n";
    o << "slam_backend_acceptance_fail_count," << m.autonomous_slam.slam_backend_acceptance_fail_count << "\n";
    o << "slam_backend_integrated_scan_count_last," << m.autonomous_slam.slam_backend_integrated_scan_count_last << "\n";
    o << "slam_backend_update_latency_s_last," << m.autonomous_slam.slam_backend_update_latency_s_last << "\n";
    o << "slam_backend_map_updated_last," << (m.autonomous_slam.slam_backend_map_updated_last ? 1 : 0) << "\n";
    o << "slam_backend_keyframe_added_last," << (m.autonomous_slam.slam_backend_keyframe_added_last ? 1 : 0) << "\n";
    o << "autonomous_slam_e2e_prelive_enabled_last," << (cfg.autonomous_slam_e2e_prelive_enabled ? 1 : 0) << "\n";
    o << "autonomous_slam_e2e_prelive_run_count," << m.autonomous_slam.autonomous_slam_e2e_prelive_run_count << "\n";
    o << "autonomous_slam_e2e_prelive_ok_last," << (m.autonomous_slam.autonomous_slam_e2e_prelive_ok_last ? 1 : 0) << "\n";
    o << "autonomous_slam_e2e_prelive_scenario_kind_last," << m.autonomous_slam.autonomous_slam_e2e_prelive_scenario_kind_last << "\n";
    o << "autonomous_slam_e2e_prelive_stage_last," << m.autonomous_slam.autonomous_slam_e2e_prelive_stage_last << "\n";
    o << "autonomous_slam_e2e_prelive_block_reason_last," << m.autonomous_slam.autonomous_slam_e2e_prelive_block_reason_last << "\n";
    o << "autonomous_slam_e2e_prelive_backend_acceptance_ok_last," << (m.autonomous_slam.autonomous_slam_e2e_prelive_backend_acceptance_ok_last ? 1 : 0) << "\n";
    o << "autonomous_slam_e2e_prelive_prelive_ok_last," << (m.autonomous_slam.autonomous_slam_e2e_prelive_prelive_ok_last ? 1 : 0) << "\n";
    o << "autonomous_slam_e2e_prelive_motion_command_count_last," << m.autonomous_slam.autonomous_slam_e2e_prelive_motion_command_count_last << "\n";
    o << "autonomous_slam_e2e_prelive_stop_command_count_last," << m.autonomous_slam.autonomous_slam_e2e_prelive_stop_command_count_last << "\n";
    o << "autonomous_slam_e2e_prelive_active_scan_command_count_last," << m.autonomous_slam.autonomous_slam_e2e_prelive_active_scan_command_count_last << "\n";
    o << "autonomous_slam_e2e_prelive_forward_backward_seen_last," << (m.autonomous_slam.autonomous_slam_e2e_prelive_forward_backward_seen_last ? 1 : 0) << "\n";
    o << "autonomous_slam_e2e_prelive_failed_case_count_last," << m.autonomous_slam.autonomous_slam_e2e_prelive_failed_case_count_last << "\n";
    o << "autonomous_slam_e2e_prelive_warning_count_last," << m.autonomous_slam.autonomous_slam_e2e_prelive_warning_count_last << "\n";
    o << "real_adapter_stubs_enabled_last," << (cfg.real_adapter_stubs_enabled ? 1 : 0) << "\n";
    o << "real_adapter_factory_create_sensor_count," << m.autonomous_slam.real_adapter_factory_create_sensor_count << "\n";
    o << "real_adapter_factory_create_motion_count," << m.autonomous_slam.real_adapter_factory_create_motion_count << "\n";
    o << "real_adapter_factory_create_slam_backend_count," << m.autonomous_slam.real_adapter_factory_create_slam_backend_count << "\n";
    o << "real_sensor_stub_ready_last," << (m.autonomous_slam.real_sensor_stub_ready_last ? 1 : 0) << "\n";
    o << "real_motion_stub_ready_last," << (m.autonomous_slam.real_motion_stub_ready_last ? 1 : 0) << "\n";
    o << "real_slam_backend_stub_ready_last," << (m.autonomous_slam.real_slam_backend_stub_ready_last ? 1 : 0) << "\n";
    o << "live_handoff_readiness_enabled_last," << (cfg.live_handoff_readiness_enabled ? 1 : 0) << "\n";
    o << "live_handoff_readiness_ok_last," << (m.autonomous_slam.live_handoff_readiness_ok_last ? 1 : 0) << "\n";
    o << "live_handoff_readiness_state_last," << m.autonomous_slam.live_handoff_readiness_state_last << "\n";
    o << "live_handoff_block_reason_last," << m.autonomous_slam.live_handoff_block_reason_last << "\n";
    o << "live_handoff_failed_case_count_last," << m.autonomous_slam.live_handoff_failed_case_count_last << "\n";
    o << "live_handoff_warning_count_last," << m.autonomous_slam.live_handoff_warning_count_last << "\n";
    o << "real_sensor_adapter_data_contract_enabled_last," << (cfg.real_sensor_adapter_data_contract_enabled ? 1 : 0) << "\n";
    o << "real_sensor_adapter_acceptance_run_count," << m.autonomous_slam.real_sensor_adapter_acceptance_run_count << "\n";
    o << "real_sensor_adapter_acceptance_ok_last," << (m.autonomous_slam.real_sensor_adapter_acceptance_ok_last ? 1 : 0) << "\n";
    o << "real_sensor_adapter_contract_status_last," << m.autonomous_slam.real_sensor_adapter_contract_status_last << "\n";
    o << "real_sensor_adapter_contract_fault_last," << m.autonomous_slam.real_sensor_adapter_contract_fault_last << "\n";
    o << "real_sensor_adapter_valid_packet_ok_last," << (m.autonomous_slam.real_sensor_adapter_valid_packet_ok_last ? 1 : 0) << "\n";
    o << "real_sensor_adapter_snapshot_build_ok_last," << (m.autonomous_slam.real_sensor_adapter_snapshot_build_ok_last ? 1 : 0) << "\n";
    o << "real_sensor_adapter_tof_range_count_last," << m.autonomous_slam.real_sensor_adapter_tof_range_count_last << "\n";
    o << "real_sensor_adapter_tof_nan_ratio_last," << m.autonomous_slam.real_sensor_adapter_tof_nan_ratio_last << "\n";
    o << "real_sensor_adapter_sync_dt_s_last," << m.autonomous_slam.real_sensor_adapter_sync_dt_s_last << "\n";
    o << "real_sensor_adapter_request_latency_s_last," << m.autonomous_slam.real_sensor_adapter_request_latency_s_last << "\n";
    o << "real_sensor_adapter_tof_estimated_sample_time_s_last," << m.autonomous_slam.real_sensor_adapter_tof_estimated_sample_time_s_last << "\n";
    o << "real_sensor_adapter_wheel_estimated_sample_time_s_last," << m.autonomous_slam.real_sensor_adapter_wheel_estimated_sample_time_s_last << "\n";
    o << "real_sensor_adapter_failed_case_count_last," << m.autonomous_slam.real_sensor_adapter_failed_case_count_last << "\n";
    o << "real_sensor_adapter_warning_count_last," << m.autonomous_slam.real_sensor_adapter_warning_count_last << "\n";
    o << "real_sensor_replay_enabled_last," << (cfg.real_sensor_replay_enabled ? 1 : 0) << "\n";
    o << "real_sensor_replay_acceptance_run_count," << m.autonomous_slam.real_sensor_replay_acceptance_run_count << "\n";
    o << "real_sensor_replay_acceptance_ok_last," << (m.autonomous_slam.real_sensor_replay_acceptance_ok_last ? 1 : 0) << "\n";
    o << "real_sensor_replay_status_last," << m.autonomous_slam.real_sensor_replay_status_last << "\n";
    o << "real_sensor_replay_fault_last," << m.autonomous_slam.real_sensor_replay_fault_last << "\n";
    o << "real_sensor_replay_parsed_record_count_last," << m.autonomous_slam.real_sensor_replay_parsed_record_count_last << "\n";
    o << "real_sensor_replay_accepted_packet_count_last," << m.autonomous_slam.real_sensor_replay_accepted_packet_count_last << "\n";
    o << "real_sensor_replay_rejected_packet_count_last," << m.autonomous_slam.real_sensor_replay_rejected_packet_count_last << "\n";
    o << "real_sensor_replay_failed_case_count_last," << m.autonomous_slam.real_sensor_replay_failed_case_count_last << "\n";
    o << "real_sensor_replay_warning_count_last," << m.autonomous_slam.real_sensor_replay_warning_count_last << "\n";
    o << "real_sensor_adapter_request_latency_mismatch_s_last," << m.autonomous_slam.real_sensor_adapter_request_latency_mismatch_s_last << "\n";
    o << "real_sensor_adapter_estimated_midpoint_error_s_last," << m.autonomous_slam.real_sensor_adapter_estimated_midpoint_error_s_last << "\n";
    o << "real_sensor_adapter_packet_sensor_time_dt_s_last," << m.autonomous_slam.real_sensor_adapter_packet_sensor_time_dt_s_last << "\n";
    o << "real_sensor_adapter_future_timestamp_skew_s_last," << m.autonomous_slam.real_sensor_adapter_future_timestamp_skew_s_last << "\n";
    o << "real_sensor_replay_invalid_record_count_last," << m.autonomous_slam.real_sensor_replay_invalid_record_count_last << "\n";
    o << "real_sensor_replay_comment_record_count_last," << m.autonomous_slam.real_sensor_replay_comment_record_count_last << "\n";
    o << "real_sensor_replay_packet_record_count_last," << m.autonomous_slam.real_sensor_replay_packet_record_count_last << "\n";
    o << "real_sensor_replay_last_validation_now_s," << m.autonomous_slam.real_sensor_replay_last_validation_now_s << "\n";
    o << "real_sensor_replay_last_packet_time_s," << m.autonomous_slam.real_sensor_replay_last_packet_time_s << "\n";
    o << "real_sensor_replay_last_effective_sensor_time_s," << m.autonomous_slam.real_sensor_replay_last_effective_sensor_time_s << "\n";
    o << "real_sensor_replay_regression_enabled_last," << (cfg.real_sensor_replay_regression_enabled ? 1 : 0) << "\n";
    o << "real_sensor_replay_regression_run_count," << m.autonomous_slam.real_sensor_replay_regression_run_count << "\n";
    o << "real_sensor_replay_regression_ok_last," << (m.autonomous_slam.real_sensor_replay_regression_ok_last ? 1 : 0) << "\n";
    o << "real_sensor_replay_regression_status_last," << m.autonomous_slam.real_sensor_replay_regression_status_last << "\n";
    o << "real_sensor_replay_regression_block_reason_last," << m.autonomous_slam.real_sensor_replay_regression_block_reason_last << "\n";
    o << "real_sensor_replay_regression_case_count_last," << m.autonomous_slam.real_sensor_replay_regression_case_count_last << "\n";
    o << "real_sensor_replay_regression_pass_count_last," << m.autonomous_slam.real_sensor_replay_regression_pass_count_last << "\n";
    o << "real_sensor_replay_regression_fail_count_last," << m.autonomous_slam.real_sensor_replay_regression_fail_count_last << "\n";
    o << "deterministic_slam_backend_enabled_last," << (cfg.deterministic_slam_backend_enabled ? 1 : 0) << "\n";
    o << "deterministic_slam_backend_ready_last," << (cfg.deterministic_slam_backend_ready ? 1 : 0) << "\n";
    o << "deterministic_slam_backend_update_call_count_last," << m.autonomous_slam.deterministic_slam_backend_update_call_count_last << "\n";
    o << "deterministic_slam_backend_accepted_update_count_last," << m.autonomous_slam.deterministic_slam_backend_accepted_update_count_last << "\n";
    o << "deterministic_slam_backend_rejected_update_count_last," << m.autonomous_slam.deterministic_slam_backend_rejected_update_count_last << "\n";
    o << "deterministic_slam_backend_keyframe_count_last," << m.autonomous_slam.deterministic_slam_backend_keyframe_count_last << "\n";
    o << "deterministic_slam_backend_valid_scan_count_last," << m.autonomous_slam.deterministic_slam_backend_valid_scan_count_last << "\n";
    o << "deterministic_slam_backend_coverage_ratio_last," << m.autonomous_slam.deterministic_slam_backend_coverage_ratio_last << "\n";
    o << "deterministic_slam_backend_yaw_coverage_ratio_last," << m.autonomous_slam.deterministic_slam_backend_yaw_coverage_ratio_last << "\n";
    o << "deterministic_slam_backend_stage_last," << m.autonomous_slam.deterministic_slam_backend_stage_last << "\n";
    o << "deterministic_slam_backend_fault_last," << m.autonomous_slam.deterministic_slam_backend_fault_last << "\n";
    o << "replay_to_slam_backend_regression_enabled_last," << (cfg.replay_to_slam_backend_regression_enabled ? 1 : 0) << "\n";
    o << "replay_to_slam_backend_regression_run_count," << m.autonomous_slam.replay_to_slam_backend_regression_run_count << "\n";
    o << "replay_to_slam_backend_regression_ok_last," << (m.autonomous_slam.replay_to_slam_backend_regression_ok_last ? 1 : 0) << "\n";
    o << "replay_to_slam_backend_regression_accepted_update_count_last," << m.autonomous_slam.replay_to_slam_backend_regression_accepted_update_count_last << "\n";
    o << "replay_to_slam_backend_regression_rejected_update_count_last," << m.autonomous_slam.replay_to_slam_backend_regression_rejected_update_count_last << "\n";
    o << "replay_to_slam_backend_regression_final_coverage_ratio_last," << m.autonomous_slam.replay_to_slam_backend_regression_final_coverage_ratio_last << "\n";
    o << "replay_to_slam_backend_regression_final_yaw_coverage_ratio_last," << m.autonomous_slam.replay_to_slam_backend_regression_final_yaw_coverage_ratio_last << "\n";
    o << "full_autonomous_slam_fake_pipeline_enabled_last," << (cfg.full_autonomous_slam_fake_pipeline_enabled ? 1 : 0) << "\n";
    o << "full_autonomous_slam_fake_pipeline_run_count," << m.autonomous_slam.full_autonomous_slam_fake_pipeline_run_count << "\n";
    o << "full_autonomous_slam_fake_pipeline_ok_last," << (m.autonomous_slam.full_autonomous_slam_fake_pipeline_ok_last ? 1 : 0) << "\n";
    o << "full_autonomous_slam_fake_pipeline_stage_last," << m.autonomous_slam.full_autonomous_slam_fake_pipeline_stage_last << "\n";
    o << "full_autonomous_slam_fake_pipeline_fault_last," << m.autonomous_slam.full_autonomous_slam_fake_pipeline_fault_last << "\n";
    o << "full_autonomous_slam_fake_pipeline_step_count_last," << m.autonomous_slam.full_autonomous_slam_fake_pipeline_step_count_last << "\n";
    o << "full_autonomous_slam_fake_pipeline_backend_accepted_update_count_last," << m.autonomous_slam.full_autonomous_slam_fake_pipeline_backend_accepted_update_count_last << "\n";
    o << "full_autonomous_slam_fake_pipeline_backend_rejected_update_count_last," << m.autonomous_slam.full_autonomous_slam_fake_pipeline_backend_rejected_update_count_last << "\n";
    o << "full_autonomous_slam_fake_pipeline_motion_command_count_last," << m.autonomous_slam.full_autonomous_slam_fake_pipeline_motion_command_count_last << "\n";
    o << "full_autonomous_slam_fake_pipeline_active_scan_command_count_last," << m.autonomous_slam.full_autonomous_slam_fake_pipeline_active_scan_command_count_last << "\n";
    o << "full_autonomous_slam_fake_pipeline_stop_command_count_last," << m.autonomous_slam.full_autonomous_slam_fake_pipeline_stop_command_count_last << "\n";
    o << "full_autonomous_slam_fake_pipeline_final_coverage_ratio_last," << m.autonomous_slam.full_autonomous_slam_fake_pipeline_final_coverage_ratio_last << "\n";
    o << "full_autonomous_slam_fake_pipeline_final_yaw_coverage_ratio_last," << m.autonomous_slam.full_autonomous_slam_fake_pipeline_final_yaw_coverage_ratio_last << "\n";
    o << "full_autonomous_slam_fake_pipeline_final_valid_scan_count_last," << m.autonomous_slam.full_autonomous_slam_fake_pipeline_final_valid_scan_count_last << "\n";
    o << "fake_map_artifact_enabled_last," << (cfg.fake_map_artifact_enabled ? 1 : 0) << "\n";
    o << "fake_map_artifact_built_last," << (m.autonomous_slam.fake_map_artifact_built_last ? 1 : 0) << "\n";
    o << "fake_map_artifact_saved_last," << (m.autonomous_slam.fake_map_artifact_saved_last ? 1 : 0) << "\n";
    o << "fake_map_artifact_status_last," << m.autonomous_slam.fake_map_artifact_status_last << "\n";
    o << "fake_map_artifact_fault_last," << m.autonomous_slam.fake_map_artifact_fault_last << "\n";
    o << "fake_map_artifact_count_last," << m.autonomous_slam.fake_map_artifact_count_last << "\n";
    o << "full_autonomous_slam_fake_pipeline_sensor_consumed_count_last," << m.autonomous_slam.full_autonomous_slam_fake_pipeline_sensor_consumed_count_last << "\n";
    o << "full_autonomous_slam_fake_pipeline_sensor_skipped_count_last," << m.autonomous_slam.full_autonomous_slam_fake_pipeline_sensor_skipped_count_last << "\n";
    o << "full_autonomous_slam_fake_pipeline_trace_event_count_last," << m.autonomous_slam.full_autonomous_slam_fake_pipeline_trace_event_count_last << "\n";
    o << "full_autonomous_slam_fake_pipeline_fake_map_built_last," << (m.autonomous_slam.full_autonomous_slam_fake_pipeline_fake_map_built_last ? 1 : 0) << "\n";
    o << "full_autonomous_slam_fake_pipeline_fake_map_saved_last," << (m.autonomous_slam.full_autonomous_slam_fake_pipeline_fake_map_saved_last ? 1 : 0) << "\n";
    o << "fake_relocalization_enabled_last," << (cfg.fake_relocalization_enabled ? 1 : 0) << "\n";
    o << "fake_relocalization_run_count," << m.autonomous_slam.fake_relocalization_run_count << "\n";
    o << "fake_relocalization_ok_last," << (m.autonomous_slam.fake_relocalization_ok_last ? 1 : 0) << "\n";
    o << "fake_relocalization_status_last," << m.autonomous_slam.fake_relocalization_status_last << "\n";
    o << "fake_relocalization_fault_last," << m.autonomous_slam.fake_relocalization_fault_last << "\n";
    o << "fake_relocalization_confidence_last," << m.autonomous_slam.fake_relocalization_confidence_last << "\n";
    o << "fake_relocalization_confidence_band_last," << m.autonomous_slam.fake_relocalization_confidence_band_last << "\n";
    o << "fake_relocalization_valid_range_count_last," << m.autonomous_slam.fake_relocalization_valid_range_count_last << "\n";
    o << "fake_relocalization_pose_valid_last," << (m.autonomous_slam.fake_relocalization_pose_valid_last ? 1 : 0) << "\n";
    o << "fake_relocalization_pose_writeback_attempted_last," << (m.autonomous_slam.fake_relocalization_pose_writeback_attempted_last ? 1 : 0) << "\n";
    o << "fake_map_relocalization_runner_enabled_last," << (cfg.fake_map_relocalization_runner_enabled ? 1 : 0) << "\n";
    o << "fake_map_relocalization_runner_run_count," << m.autonomous_slam.fake_map_relocalization_runner_run_count << "\n";
    o << "fake_map_relocalization_runner_ok_last," << (m.autonomous_slam.fake_map_relocalization_runner_ok_last ? 1 : 0) << "\n";
    o << "fake_map_relocalization_runner_map_loaded_last," << (m.autonomous_slam.fake_map_relocalization_runner_map_loaded_last ? 1 : 0) << "\n";
    o << "fake_relocalization_readiness_gate_enabled_last," << (cfg.fake_relocalization_readiness_gate_enabled ? 1 : 0) << "\n";
    o << "fake_relocalization_readiness_gate_ok_last," << (m.autonomous_slam.fake_relocalization_readiness_gate_ok_last ? 1 : 0) << "\n";
    o << "fake_relocalization_readiness_gate_status_last," << m.autonomous_slam.fake_relocalization_readiness_gate_status_last << "\n";
    o << "fake_relocalization_readiness_gate_block_reason_last," << m.autonomous_slam.fake_relocalization_readiness_gate_block_reason_last << "\n";
    o << "fake_autonomous_slam_product_acceptance_enabled_last," << (cfg.fake_autonomous_slam_product_acceptance_enabled ? 1 : 0) << "\n";
    o << "fake_autonomous_slam_product_acceptance_run_count," << m.autonomous_slam.fake_autonomous_slam_product_acceptance_run_count << "\n";
    o << "fake_autonomous_slam_product_acceptance_ok_last," << (m.autonomous_slam.fake_autonomous_slam_product_acceptance_ok_last ? 1 : 0) << "\n";
    o << "fake_autonomous_slam_product_acceptance_status_last," << m.autonomous_slam.fake_autonomous_slam_product_acceptance_status_last << "\n";
    o << "fake_autonomous_slam_product_acceptance_block_reason_last," << m.autonomous_slam.fake_autonomous_slam_product_acceptance_block_reason_last << "\n";
    o << "fake_autonomous_slam_product_acceptance_mapping_ok_last," << (m.autonomous_slam.fake_autonomous_slam_product_acceptance_mapping_ok_last ? 1 : 0) << "\n";
    o << "fake_autonomous_slam_product_acceptance_relocalization_ok_last," << (m.autonomous_slam.fake_autonomous_slam_product_acceptance_relocalization_ok_last ? 1 : 0) << "\n";
    o << "fake_autonomous_slam_product_acceptance_manifest_valid_last," << (m.autonomous_slam.fake_autonomous_slam_product_acceptance_manifest_valid_last ? 1 : 0) << "\n";
    o << "multi_tof_raw_data_contract_enabled_last," << (cfg.multi_tof_raw_data_contract_enabled ? 1 : 0) << "\n";
    o << "multi_tof_raw_data_contract_acceptance_run_count," << m.autonomous_slam.multi_tof_raw_data_contract_acceptance_run_count << "\n";
    o << "multi_tof_raw_data_contract_acceptance_ok_last," << (m.autonomous_slam.multi_tof_raw_data_contract_acceptance_ok_last ? 1 : 0) << "\n";
    o << "multi_tof_raw_data_contract_status_last," << m.autonomous_slam.multi_tof_raw_data_contract_status_last << "\n";
    o << "multi_tof_raw_data_contract_fault_last," << m.autonomous_slam.multi_tof_raw_data_contract_fault_last << "\n";
    o << "multi_tof_raw_data_contract_valid_tof_count_last," << m.autonomous_slam.multi_tof_raw_data_contract_valid_tof_count_last << "\n";
    o << "multi_tof_raw_data_contract_front_ok_last," << (m.autonomous_slam.multi_tof_raw_data_contract_front_ok_last ? 1 : 0) << "\n";
    o << "multi_tof_raw_data_contract_left_ok_last," << (m.autonomous_slam.multi_tof_raw_data_contract_left_ok_last ? 1 : 0) << "\n";
    o << "multi_tof_raw_data_contract_right_ok_last," << (m.autonomous_slam.multi_tof_raw_data_contract_right_ok_last ? 1 : 0) << "\n";
    o << "multi_tof_raw_data_contract_failed_case_count_last," << m.autonomous_slam.multi_tof_raw_data_contract_failed_case_count_last << "\n";
    o << "multi_tof_raw_data_contract_warning_count_last," << m.autonomous_slam.multi_tof_raw_data_contract_warning_count_last << "\n";
    o << "static_scan_boost_updates," << m.static_scan_boost_updates << "\n";
    o << "low_odom_quality_pauses," << m.low_odom_quality_pauses << "\n";
    o << "tof_unhealthy_pauses," << m.tof_unhealthy_pauses << "\n";
    o << "tof_correction_attempts," << m.tof_correction_attempts << "\n";
    o << "tof_correction_accepts," << m.tof_correction_accepts << "\n";
    o << "tof_correction_rejects," << m.tof_correction_rejects << "\n";
    o << "tof_correction_mean_residual," << (m.tof_correction_attempts ? m.tof_correction_residual_sum / m.tof_correction_attempts : 0.0) << "\n";
    o << "tof_correction_odom_residual_mean," << (m.tof_correction_attempts ? m.tof_correction_odom_residual_sum / m.tof_correction_attempts : 0.0) << "\n";
    o << "tof_correction_best_residual_mean," << (m.tof_correction_attempts ? m.tof_correction_residual_sum / m.tof_correction_attempts : 0.0) << "\n";
    o << "tof_correction_improvement_mean," << (m.tof_correction_attempts ? m.tof_correction_improvement_sum / m.tof_correction_attempts : 0.0) << "\n";
    o << "tof_correction_best_shift_mean," << (m.tof_correction_attempts ? m.tof_correction_best_shift_sum / m.tof_correction_attempts : 0.0) << "\n";
    o << "tof_correction_max_dx," << m.tof_correction_max_dx << "\n";
    o << "tof_correction_max_dyaw," << m.tof_correction_max_dyaw << "\n";
    o << "pose_quality_mean," << (m.localization_updates ? m.pose_quality_sum / m.localization_updates : 0.0) << "\n";
    o << "pose_quality_min," << (m.localization_updates ? m.pose_quality_min : 0.0) << "\n";
    o << "localization_confidence_mean," << (m.localization_updates ? m.localization_confidence_sum / m.localization_updates : 0.0) << "\n";
    o << "localization_confidence_min," << (m.localization_updates ? m.localization_confidence_min : 0.0) << "\n";
    o << "spin_scan_attempts," << m.spin_scan_attempts << "\n";
    o << "spin_scan_completed," << m.spin_scan_completed << "\n";
    o << "spin_scan_failed," << m.spin_scan_failed << "\n";
    o << "spin_scan_matched," << m.spin_scan_matched << "\n";
    o << "spin_scan_usable," << m.spin_scan_usable << "\n";
    o << "spin_scan_valid_bins_mean," << (m.spin_scan_attempts ? m.spin_scan_valid_bins_sum / m.spin_scan_attempts : 0.0) << "\n";
    o << "spin_scan_valid_bin_ratio_mean," << (m.spin_scan_attempts ? m.spin_scan_valid_bin_ratio_sum / m.spin_scan_attempts : 0.0) << "\n";
    o << "spin_scan_reliability_mean," << (m.spin_scan_attempts ? m.spin_scan_reliability_sum / m.spin_scan_attempts : 0.0) << "\n";
    o << "spin_scan_reliability_min," << (m.spin_scan_attempts ? m.spin_scan_reliability_min : 0.0) << "\n";
    o << "spin_scan_multimodal_count," << m.spin_scan_multimodal_count << "\n";
    o << "spin_scan_flat_curve_count," << m.spin_scan_flat_curve_count << "\n";
    o << "spin_scan_edge_best_count," << m.spin_scan_edge_best_count << "\n";
    o << "encoder_rejected_updates," << loc.rejected_encoder_updates() << "\n";
    o << "encoder_left_reads," << encoder_stats.left_reads << "\n";
    o << "encoder_right_reads," << encoder_stats.right_reads << "\n";
    o << "encoder_left_errors," << encoder_stats.left_errors << "\n";
    o << "encoder_right_errors," << encoder_stats.right_errors << "\n";
    o << "encoder_left_total_ticks," << encoder_stats.left_total_ticks << "\n";
    o << "encoder_right_total_ticks," << encoder_stats.right_total_ticks << "\n";
    o << "encoder_left_rpm," << encoder_stats.left_rpm << "\n";
    o << "encoder_right_rpm," << encoder_stats.right_rpm << "\n";
    o << "encoder_left_read_ok_last," << (cfg.encoder_source == "cjc_bl4820_uart" ? (encoder_stats.left_read_ok ? 1 : 0) : 1) << "\n";
    o << "encoder_right_read_ok_last," << (cfg.encoder_source == "cjc_bl4820_uart" ? (encoder_stats.right_read_ok ? 1 : 0) : 1) << "\n";
    o << "encoder_left_latency_us_last," << encoder_stats.left_latency_us << "\n";
    o << "encoder_right_latency_us_last," << encoder_stats.right_latency_us << "\n";
    o << "encoder_pair_skew_us_last," << encoder_stats.encoder_pair_skew_us << "\n";
    o << "encoder_pair_skew_ok_last," << (cfg.encoder_source == "cjc_bl4820_uart" ? (encoder_stats.encoder_pair_skew_ok ? 1 : 0) : 1) << "\n";
    o << "encoder_left_timeout_count," << encoder_stats.left_timeout_count << "\n";
    o << "encoder_right_timeout_count," << encoder_stats.right_timeout_count << "\n";
    o << "encoder_left_parse_error_count," << encoder_stats.left_parse_error_count << "\n";
    o << "encoder_right_parse_error_count," << encoder_stats.right_parse_error_count << "\n";
    o << "encoder_left_checksum_error_count," << encoder_stats.left_checksum_error_count << "\n";
    o << "encoder_right_checksum_error_count," << encoder_stats.right_checksum_error_count << "\n";
    o << "encoder_left_status_error_count," << encoder_stats.left_status_error_count << "\n";
    o << "encoder_right_status_error_count," << encoder_stats.right_status_error_count << "\n";
    o << "encoder_pair_skew_bad_count," << encoder_stats.encoder_pair_skew_bad_count << "\n";
    o << "encoder_uart_checksum_errors," << encoder_stats.uart_checksum_errors << "\n";
    o << "encoder_uart_timeout_errors," << encoder_stats.uart_timeout_errors << "\n";
    o << "encoder_uart_status_errors," << encoder_stats.uart_status_errors << "\n";
    o << "encoder_uart_frame_errors," << encoder_stats.uart_frame_errors << "\n";
    o << "encoder_jump_rejects," << encoder_stats.jump_rejects << "\n";
    o << "encoder_left_unhealthy," << (encoder_stats.left_unhealthy ? 1 : 0) << "\n";
    o << "encoder_right_unhealthy," << (encoder_stats.right_unhealthy ? 1 : 0) << "\n";
    o << "gyro_spikes," << loc.gyro_spikes() << "\n";
    o << "gyro_bias_adapt_updates," << loc.bias_adapt_updates() << "\n";
    o << "final_gyro_bias_rad_s," << loc.gyro_bias() << "\n";
    o << "localizer_initialized," << (loc.initialized() ? 1 : 0) << "\n";
    o << "localizer_yaw_correction_offset_rad," << loc.yaw_correction_offset_rad() << "\n";
    o << "localizer_yaw_correction_apply_count," << loc.yaw_correction_apply_count() << "\n";
    o << "localizer_yaw_correction_total_abs_deg," << loc.yaw_correction_total_abs_deg() << "\n";
    o << "localizer_yaw_correction_last_reason," << loc.yaw_correction_last_reason() << "\n";
    for (const auto &id : {"front", "left", "right"}) {
        const auto &st = health.by_id.at(id);
        o << id << "_hit_rate," << st.hit_rate() << "\n";
        o << id << "_reject_rate," << st.reject_rate() << "\n";
        o << id << "_gap_count," << st.gaps << "\n";
        o << id << "_confidence_mean," << st.confidence_mean() << "\n";
        o << id << "_unhealthy," << (st.unhealthy(cfg) ? 1 : 0) << "\n";
    }
    o << "map_chunks," << gs.chunks << "\n";
    o << "map_touched_cells," << gs.touched_cells << "\n";
    o << "map_width_cells," << gs.width_cells << "\n";
    o << "map_height_cells," << gs.height_cells << "\n";
    o << "map_occupied_cells," << gs.occupied_cells << "\n";
    o << "map_free_cells," << gs.free_cells << "\n";
    o << "map_unknown_cells," << gs.unknown_cells << "\n";
}

} // namespace robot_slamd
